theme: minima

header_pages:
  - start/index.md
  - tutorials/index.md
  - reference/index.md

github_repo: "https://github.com/MagicIdentity/Developers"
github_base: "https://github.com/MagicIdentity/Developers/tree/main"
jsdocs_base: "https://webdaemon.online/dev/static/lib/docs/index.js"
